@startuml
'https://plantuml.com/class-diagram

hide empty methods

enum COMMAND

class Command{
- COMMAND : command
+ COMMAND : getCommand()
}

abstract class View{
+ COMMAND : getCommand()
}

Command .. COMMAND
View -r-> Command

note right of Command : Lida com o input
@enduml