@startuml
'https://plantuml.com/component-diagram


abstract class Enemy{
+ move() : void
}

class Enemies{
+ moveEnemies() : void
}

class Dragon{
+ move() : void
}

class Dementor{
+ move() : void
}

Enemies *-- Enemy
Dragon -u-|> Enemy
Dementor -u-|> Enemy

@enduml