@startuml
'https://plantuml.com/component-diagram


abstract class Enemy{
{abstract} + kill() : int
}

class Dragon{
+ kill() : int
}


class Dementor{
+ kill() : int
}

Dragon -u-|> Enemy
Dementor -u-|> Enemy

@enduml